<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKyN2rx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKyN2rx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAKyN2rx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAKyN2rx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAKyN2rx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AKyN2rx',
    'container.build_id' => 'c152033f',
    'container.build_time' => 1582496924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKyN2rx');
