<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'entrada' => [[], ['_controller' => 'App\\Controller\\EntradaController::index'], [], [['text', '/entrada']], [], []],
    'usuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::registro'], [], [['text', '/usuario']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'entradas' => [[], ['_controller' => 'App\\Controller\\EntradaController::index'], [], [['text', '/entradas']], [], []],
    'crear' => [[], ['_controller' => 'App\\Controller\\EntradaController::crear'], [], [['text', '/crear']], [], []],
    'detalle' => [['id'], ['_controller' => 'App\\Controller\\EntradaController::detalle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/detalle']], [], []],
    'editar' => [['id'], ['_controller' => 'App\\Controller\\EntradaController::actualizar'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/editar']], [], []],
    'eliminar' => [['id'], ['_controller' => 'App\\Controller\\EntradaController::eliminar'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/eliminar']], [], []],
    'mis_blogs' => [[], ['_controller' => 'App\\Controller\\EntradaController::misEntradas'], [], [['text', '/mis-blogs']], [], []],
    'contacto' => [[], ['_controller' => 'App\\Controller\\ContactoController::crearContacto'], [], [['text', '/contacto']], [], []],
    'registro' => [[], ['_controller' => 'App\\Controller\\UsuarioController::registro'], [], [['text', '/registro']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\UsuarioController::login'], [], [['text', '/login']], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], []],
];
